apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "micro-service-2.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "micro-service-2.name" . }}
    helm.sh/chart: {{ include "micro-service-2.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "micro-service-2.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "micro-service-2.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: spring.datasource.url
              value: "jdbc:postgresql://postgres-service:5432/"
            - name: spring.jpa.properties.hibernate.dialect
              value: "org.hibernate.dialect.PostgreSQLDialect"
            - name: spring.datasource.username
              value: "postgres"
            - name: spring.datasource.password
              value: "postgres"
            - name: server.port
              value: "9091"
          ports:
            - name: http
              containerPort: 9091
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /actuator/health
              port: http
          readinessProbe:
            httpGet:
              path: /actuator/health
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
