# Base Alpine Linux based image with OpenJDK JRE only
FROM openjdk:8-jre-alpine


# copy application WAR (with libraries inside)
COPY nokia-micro-service-1/target/nokia-micro-serivice-1-0.0.1-SNAPSHOT.jar /nokia-micro-serivice-1-0.0.1-SNAPSHOT.jar


#Expose Port to access from outside container
EXPOSE 9090


# specify default command
CMD ["/usr/bin/java", "-jar","/nokia-micro-serivice-1-0.0.1-SNAPSHOT.jar"]
